import {onRequest as api, readBody} from './api/auto.js';
const ORIGIN='https://akurunamedia.id';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const digest=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).join(',');
function page(body,status=200){return new Response(`<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Otomasi · Akuruna Media</title><style>body{margin:0;background:#081a14;color:#edf9f2;font:17px system-ui;padding:28px}main{max-width:950px;margin:auto}p{line-height:1.6}input,button{padding:14px;font:inherit;border-radius:8px}input{max-width:90%;width:420px;background:#142e23;color:white;border:1px solid #668575}button{background:#63dea1;border:0;cursor:pointer}section{background:#142e23;padding:20px;margin:20px 0;border-radius:12px}a{color:#79e6b1}td,th{text-align:left;padding:12px;border-bottom:1px solid #456}table{width:100%;font-size:14px}code{overflow-wrap:anywhere}.scroll{overflow:auto}</style><main><p>AKURUNA MEDIA · OTOMASI</p>${body}<p><a href="/agent-write">Buat draf manual</a> · <a href="/agent-admin">Koneksi WordPress</a></p></main></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'same-origin','X-Robots-Tag':'noindex, nofollow','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'"}});}
export async function onRequest({request,env}){
  if(new URL(request.url).origin!==ORIGIN)return page('<p>Buka akurunamedia.id/agent-auto.</p>',403);
  if(request.method==='GET')return page('<h1>Periksa otomasi berita</h1><p>Lihat koneksi Instagram dan hasil pekerjaan terakhir.</p><form method="post"><p><label>Kunci admin<br><input name="key" type="password" autocomplete="off" required minlength="32" maxlength="512"></label></p><button>Periksa status</button></form>');
  if(request.method!=='POST'||request.headers.get('Origin')!==ORIGIN)return page('<p>Asal permintaan tidak sesuai.</p>',403);
  try{
    const b=new URLSearchParams(await readBody(request,4096));
    if(!env.AGENT_ADMIN_KEY||await digest(b.get('key')||'')!==await digest(env.AGENT_ADMIN_KEY))return page('<p>Kunci admin salah.</p>',401);
    const r=await api({env,request:new Request(ORIGIN+'/api/auto',{method:'POST',headers:{Authorization:'Bearer '+env.AUTO_RUN_KEY},body:JSON.stringify({action:'inspect'})})});
    const data=await r.json();if(!r.ok)return page('<h1>Konfigurasi belum lengkap</h1><p>'+esc(data.error)+'. Periksa AUTO_RUN_KEY, AGENT_DB, dan koneksi WordPress.</p>',r.status);
    const names={off:'Dijeda',draft:'Uji: simpan draf',publish:'Publikasi diizinkan'};
    return page('<h1>'+esc(names[data.mode])+'</h1><p>Maksimal '+data.daily_limit+' pekerjaan per hari WIB. Jadwal berjalan hanya jika AUTO_ENABLED di GitHub bernilai true.</p><section><h2>Koneksi sosial</h2>'+data.connections.map(c=>'<p>'+esc(c.label)+' · '+esc(c.display_name)+'<br>Service: <code>'+esc(c.service)+'</code> · ID '+esc(c.id)+'</p>').join('')+'<p>Service Instagram pada konfigurasi: <code>'+esc(data.instagram_service||'belum diisi')+'</code></p></section><h2>Pekerjaan terakhir</h2><div class="scroll"><table><tr><th>Waktu UTC</th><th>Status</th><th>Artikel</th></tr>'+data.jobs.map(j=>'<tr><td>'+esc(j.created)+'</td><td>'+esc(j.state)+'<br>'+esc(j.note)+'</td><td>'+(j.post_id?'<a href="https://wordpress.com/post/'+encodeURIComponent(data.site)+'/'+encodeURIComponent(j.post_id)+'">Buka WordPress</a>':'<code>'+esc(j.id.slice(0,12))+'</code>')+'</td></tr>').join('')+'</table></div><p>published_wp berarti artikel sudah terbit dan permintaan berbagi dikirim. Periksa Instagram untuk memastikan gambar dan caption benar-benar masuk.</p>');
  }catch{return page('<p>Pemeriksaan gagal. Coba lagi; halaman ini tidak menerbitkan apa pun.</p>',502);}
}
